LAMMPS (15 Jun 2023 - Development - f70df7834e-modified)
/home/jmgoff/Software/mala_frc_combine/mala/descriptors/lammps_utils.py:102: RuntimeWarning: overflow encountered in cast
  return array_np.astype(DEFAULT_NP_DATA_DTYPE)
predictor vars {'parameters_full': <mala.common.parameters.Parameters object at 0x7fb11c274550>, 'parameters': <mala.common.parameters.ParametersRunning object at 0x7fb11c2745b0>, 'network': FeedForwardNet(
  (layers): ModuleList(
    (0): Linear(in_features=48, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=11, bias=True)
    (3): ReLU()
  )
), 'data': <mala.datahandling.data_handler.DataHandler object at 0x7fb11c274460>, 'test_data_loader': None, 'number_of_batches_per_snapshot': 0, 'target_calculator': <mala.targets.ldos.LDOS object at 0x7fb11c275690>, 'input_data': None, 'output_data': None}
predictor vars {'parameters': <mala.common.parameters.ParametersData object at 0x7fb11c2746a0>, 'use_ddp': False, 'target_calculator': <mala.targets.ldos.LDOS object at 0x7fb11c275690>, 'descriptor_calculator': <mala.descriptors.ace.ACE object at 0x7fb11c2757b0>, '_input_dimension': 0, '_output_dimension': 0, 'nr_snapshots': 0, 'input_data_scaler': <mala.datahandling.data_scaler.DataScaler object at 0x7fb11c22bfd0>, 'output_data_scaler': <mala.datahandling.data_scaler.DataScaler object at 0x7fb11c2743a0>, 'nr_training_data': 0, 'nr_test_data': 0, 'nr_validation_data': 0, 'nr_training_snapshots': 0, 'nr_test_snapshots': 0, 'nr_validation_snapshots': 0, 'training_data_inputs': tensor([]), 'validation_data_inputs': tensor([]), 'test_data_inputs': tensor([]), 'training_data_outputs': tensor([]), 'validation_data_outputs': tensor([]), 'test_data_outputs': tensor([]), 'training_data_sets': [], 'validation_data_sets': [], 'test_data_sets': [], 'mini_batch_size': 40, 'grid_dimension': [18, 18, 27], 'grid_size': 0}
predictor vars {'_configuration': {'gpu': False, 'ddp': False, 'mpi': False, 'device': 'cpu', 'openpmd_configuration': {}, 'openpmd_granularity': 1, 'lammps': True}, 'trainingtype': 'Adam', 'learning_rate': 1e-05, 'max_number_epochs': 100, 'verbosity': True, 'mini_batch_size': 40, 'weight_decay': 0, 'early_stopping_epochs': 0, 'early_stopping_threshold': 0, 'learning_rate_scheduler': None, 'learning_rate_decay': 0.1, 'learning_rate_patience': 0, 'num_workers': 0, 'use_shuffling_for_samplers': True, 'checkpoints_each_epoch': 0, 'checkpoint_name': 'checkpoint_mala', 'visualisation': 0, 'visualisation_dir': './mala_logging', 'visualisation_dir_append_date': True, '_during_training_metric': 'ldos', '_after_before_training_metric': 'ldos', 'inference_data_grid': [0, 0, 0], 'use_mixed_precision': False, '_use_graphs': False, 'training_report_frequency': 1000, 'profiler_range': None}
param grid [18, 18, 27]
grid size 0
global max cutoff (angstrom) 5.71
all basis functions 344 grid subset 48
filepath in ace desc script /home/jmgoff/Software/mala_frc_combine/mala/descriptors/
file /home/jmgoff/Software/mala_frc_combine/mala/descriptors/in.acegrid.python
array_np has nan False
array_np has inf False False
torch.Size([8748, 48]) torch.Size([1, 48])
Had to readjust batch size from 40 to 54
Total wall time: 0:00:00
Traceback (most recent call last):
  File "/home/jmgoff/Software/mala_frc_combine/examples/mala_ace_frc_coeff_ex/test.py", line 163, in <module>
    pre_force_callback(lmp)
  File "/home/jmgoff/Software/mala_frc_combine/examples/mala_ace_frc_coeff_ex/test.py", line 106, in pre_force_callback
    mala_forces = ldos_calculator.atomic_forces
  File "/home/jmgoff/anaconda3/envs/mliap_devel/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/jmgoff/Software/mala_frc_combine/mala/targets/ldos.py", line 300, in atomic_forces
    raise Exception("No cached LDOS available to calculate this "
Exception: No cached LDOS available to calculate this property.
